FLOWFACTCorp/ff-api-services

src/service/SprengnetterService.ts
=> Adding Ressources To Sprengnetter Service for Market-Analysis-Tool

package.json, src/service/BehaviourService.ts, yarn.lock
- post events in background, one request at a time
=> add track function

src/service/CompanyService.ts
Added /company/ to the mapping to make it work.
=> Right Ressource-Mapping

package.json, src/service/PortalManagementService/PortalController.ts
Add optional companyMarket request parameter to filter predefined portals
=> FLOW-8549: Add companyMarket request param to fetch predefined portals

src/service/PortalManagementService/PortalController.ts, src/service/PortalManagementService/PortalManagementService.Types.ts
=> FLOW-10839: add index to type

src/service/UserService/AdditionalDataController.ts, src/service/UserService/FieldConfigController.ts, src/service/UserService/UserService.Types.ts, src/service/UserService/index.ts
**Jira task**
https://flowfact.atlassian.net/browse/FLOW-11059
**What changed**
Endpoints for CRUD operations related to `user-service`
- FieldConfigController endpoints for storing/modifying additional field configuration for company scope by admin users
- AdditionalDataController endpoints for storing and modifying data filled in additional fields for user scope
=> feat FLOW-11059 User additional data and Additional fields Config

src/service/DocumentTemplateService/DocumentTemplateService.Types.ts
=> FLOW-9500 add type slack with fallback to string

src/service/EntityService.ts
Add prefix handling to ff-api-services
PR for platform-apps will follow
=> Add prefix handling

src/http/APIMapping.ts, src/index.ts, src/service/EntityShareService/EntityShareAccessController.ts, src/service/EntityShareService/EntityShareService.Types.ts, src/service/EntityShareService/EntityShareTokenController.ts, src/service/EntityShareService/index.ts
Endpoint for:
- entity share token management,
- entity access for other company.
=> Entity share service endpoints

src/service/UserService/UserService.Types.ts
=> FLOW-12612

src/service/DynamicLayoutService/WidgetLayoutTypes.ts
Load default category in the preview mode on entities list
=> FLOW-11795

src/service/ViewDefinitionService/ViewDefinitionService.Types.ts
Extend ViewType type by 'QUICK_CREATE'
=> FLOW-12864-improve-adding-entity-from-header

src/service/UserLogoutService/UserLogoutController.ts, src/service/UserLogoutService/UserLogoutService.Types.ts
UserlogoutService can now accept different types. So i have to extend the interfaces and types
<br />
___
<br />
__
=> FLOW-13712: extend types in UserLogoutService

src/service/UserLogoutService/UserLogoutService.Types.ts
=> FLOW-13712: fix types

src/index.ts, src/service/PoiService/PoiSearchController.ts, src/service/PoiService/PoiService.Types.ts, src/service/PoiService/index.ts
Endpoint for fetching Points of Interest list that will be used in POI Widget. Returns points for given latitude, longitude, categories and radius.
<br />
___
<br />
___
- Jira: https://flowfact.atlassian.net/browse/FLOW-13046
<br />
=> FLOW-13046 Endpoint for fetching POI list

src/service/GeoInformationService/GeoPolygonController.ts
No dependencies.
Update method signature according to swagger: https://api.development.cloudios.flowfact-dev.cloud/geo-information-service/public/swagger-ui.html#/geo-polygon-controller
___
- [/] My code follows the style guidelines of this project
- [/] I have performed a self-review of my own code
- [/] I have commented my code, particularly in hard-to-understand areas
- [/] My changes generate no new warnings (ESLint)
<br />
___
- Jira: https://flowfact.atlassian.net/browse/FLOW-10398
<br />
=> FLOW-10398: updatePolygonByName - fix method signature

src/service/PreconditionService/NylasPreconditionController.ts
Connects new endpoint to check for incorrect mail accounts (solves Nylas issues)
<br />
___
<br />
___
- Jira: https://flowfact.atlassian.net/browse/FLOW-13959
=> Add method to call new endpoint

src/service/PoiService/PoiService.Types.ts
POI types added to api-services.
<br />
___
<br />
___
- Jira: 
<br />
=> FLOW-13046 POI types added

src/service/UserLogoutService/UserLogoutController.ts
Rename method, otherwise can be misleading
___
<br />
___
- Jira: 
<br />
=> FLOW-12921: Rename method

src/service/UserLogoutService/UserLogoutController.ts, src/service/UserLogoutService/UserLogoutService.Types.ts
Add namespace
___
<br />
___
- Jira: 
<br />
=> FLOW-12921: Add namespace

package.json, src/service/FilterDefinitionService/FilterDefinitionService.Types.ts
- adds new `isGlobal` and `defaultFilter` boolean flags to reflect service changes
___
<br />
___
- Jira: 
<br />
=> FLOW-11413: add new fields to filter definition

src/service/UserLogoutService/UserLogoutService.Types.ts
=> None-Jira: Add timezone to trigger

package.json, yarn.lock
=> None-Jira: Upgrade node-flowdsl

src/http/APIClient.ts
For the switch from user to entity and the ability to connect multiple companies to a single user it is required that we add the companyId header to all requests.
___
- ...
- ...
- ...
<br />
___
<br />
___
- Jira: 
<br />
=> FLOW-14116: Add company to all request headers when present

src/service/MailchimpSyncIntegrationService/MailchimpController.ts, src/service/MailchimpSyncIntegrationService/MailchimpService.Types.ts
A new endpoint that allows to synchronize selected contacts and assign them to given mailchimp subgroup.
<br />
___
<br />
___
- Jira: https://flowfact.atlassian.net/browse/FLOW-14002
<br />
=> FLOW-14002 Endpoint to synchronize selected contacts with Mailchimp

src/service/IS24PublishService/IS24RealEstateController.ts, src/service/IS24PublishService/index.ts
A new endpoint that allows deleting IS24 realestate.
<br />
___
<br />
___
- Jira: https://flowfact.atlassian.net/browse/FLOW-14429
<br />
=> feat: FLOW-14429 Delete IS24 estate resource added.

src/service/PoiService/PoiService.Types.ts
Change of PoiData interface to simplify the handling of POI address.
<br />
___
<br />
___
- Jira: https://flowfact.atlassian.net/browse/FLOW-14622
<br />
=> FLOW-14622 PoiData interface updated

src/service/PortalManagementService/CompanyEstateAttributesController.ts, src/service/PortalManagementService/PortalEstateController.ts, src/service/PortalManagementService/PortalManagementService.Types.ts, src/service/PortalManagementService/index.ts
Added company estate attributes resources for portal mgm service. 
___
- added CompanyEstateAttributesController
<br />
___
- [/] My code follows the style guidelines of this project
<br />
___
- Jira: 
<br />
DO IT FAST OR I CALL THE POLICE :trollface:
=> FLOW-14251

src/http/APIMapping.ts, src/index.ts, src/service/EntityFieldCalculationService/EntityFieldCalculationController.ts, src/service/EntityFieldCalculationService/EntityFieldCalculationService.Types.ts, src/service/EntityFieldCalculationService/index.ts
Provide api call for field calculation service (formula validation). 
<br />
___
<br />
___
- Jira: https://flowfact.atlassian.net/browse/FLOW-14713
<br />
=> Field calculation service

src/service/GeoInformationService/GeoInformationService.Types.ts, src/service/GeoInformationService/GeoPolygonController.ts, src/service/common/types/TranslatableText.ts
This PR is about to align types with backend.
There are no braking changes in platform-app, so this PR can be merged without any dependencies
<br />
___
- [/] My code follows the style guidelines of this project
- [/] I have performed a self-review of my own code
- [/] I have commented my code, particularly in hard-to-understand areas
- [/] My changes generate no new warnings (ESLint)
<br />
___
- Jira: https://flowfact.atlassian.net/browse/FLOW-10395
=> FLOW-10395: Update GeoInformationService

src/service/EmailService/SendController.ts, src/service/ViewDefinitionService/ViewDefinitionService.Types.ts, src/service/ViewDefinitionService/ViewDefinitionV2.Types.ts
New field in view-definition to specify JSON type fields subfield (displaying purposes).
Change send email endpoint path.
<br />
___
<br />
___
- Jira: https://flowfact.atlassian.net/browse/FLOW-14801
- https://flowfact.atlassian.net/browse/FLOW-15170
=> FLOW-14801 new subfields for JSON type in view definition

src/http/APIMapping.ts, src/index.ts, src/service/AlternativeCompanyDataService/AlternativeCompanyDataController.ts, src/service/AlternativeCompanyDataService/AlternativeCompanyDataService.Types.ts, src/service/AlternativeCompanyDataService/index.ts
Prepared api calls for alternative data configurations.
<br />
___
<br />
___
- Jira: https://flowfact.atlassian.net/browse/FLOW-14511
<br />
=> Flow 14511

src/service/PreconditionService/NylasPreconditionController.ts
___
- added new endpoints for checking preconditions of nylas email accounts
<br />
___
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings (ESLint)
<br />
___
- Jira: 
<br />
=> FLOW-14121: added new endpoints for nylas account checks

src/service/CompanyService/CompanyService.Types.ts
Add additional company market in prep for franchise edition.
=> FLOW-15182: Company market franchise

src/http/APIMapping.ts
- readded clientNotificationService
- Jira: -
=> readded clientNotificationService

src/service/ViewDefinitionService/ViewDefinitionService.Types.ts
Update view definition category jsonFieldsConfig, according to new schema in API.
___
<br />
___
- Jira: 
<br />
=> FLOW-15446 update view-definition category jsonFieldsConfig types

src/service/InteractiveExposeV2Service/InteractiveExposeV2Service.Types.ts
___
- add missing properties to IEXBlastItem
<br />
___
<br />
___
- Jira: FLOW-14766
<br />
=> FLOW-14766: fix type of IEXBlastItem

src/service/UserService/UserService.Types.ts
Changes needed for https://github.com/FLOWFACTCorp/platform-apps/pull/2031
=> extend AdditionalFieldType enum

src/service/EmailService/RespondController.ts
Added additional param for a forwarding email request. 
The forward email body should be generated on FE in the same way it works now for reply functionality.
<br />
___
<br />
___
- Jira: https://flowfact.atlassian.net/browse/FLOW-15900
<br />
=> fix: FLOW-15900

src/service/PortalManagementService/PortalManagementService.Types.ts
To better handle deleting from IS24 (instead of just deactivating)
the PortalManagementService was extended to handle 3rd status
next to Online and Offline: Delete.
This extends this change to types in ff-api-service
<br />
___
<br />
___
- Jira: https://flowfact.atlassian.net/browse/FLOW-15562?atlOrigin=eyJpIjoiZDA3ZmE5YzI1ZjY4NDE1YjgwMTY1M2UxMDFmY2JmYzYiLCJwIjoiaiJ9
<br />
=> FLOW-15562 Adds new DELETE status

package.json, yarn.lock
___
- update node-flowdsl because of fixed groupBy type
<br />
___
<br />
___
- Jira: FLOW-16035
<br />
=> FLOW-16035: update node-flowdsl because of fixed groupBy type

src/service/ExcelExporterService/ExcelExporterController.ts
-   added two new Endpoints for the Search Export Excel Button
-   Jira: FLOW-15735
=> FLOW-15735: add search endpoints

src/http/APIClient.ts, src/service/EmailService/BodyController.ts, src/service/EmailService/ConfigurationController.ts, src/service/EmailService/NotificationController.ts, src/service/EmailService/RespondController.ts, src/service/EmailService/SendController.ts, src/service/EmailService/SyncController.ts, src/service/EmailService/index.ts, src/service/EntityService.ts, src/service/FieldCalculationService/index.ts, src/service/GeoInformationService/GeoInformationService.Types.ts, src/service/IS24PublishService/IS24Publish.Types.ts, src/service/IS24PublishService/IS24PublishController.ts, src/service/InteractiveExposeV2Service/InteractiveExposeV2Controller.ts, src/service/InteractiveExposeV2Service/TemplatesRepositoryController.ts, src/service/MailchimpSyncIntegrationService/MailchimpController.ts, src/service/MultimediaService/AlbumAssignmentController.ts, src/service/PlaceholderService/PlaceholderController.ts, src/service/PortalManagementService/CompanyEstateAttributesController.ts, src/service/PortalManagementService/index.ts, src/service/UserLogoutService/UserLogoutController.ts, src/service/UserLogoutService/UserLogoutService.Types.ts, src/service/common/types/TranslatableText.ts
Refactored ApiClient a bit, for better types
=> Refactor ApiClient for better types

src/service/MatchmakingService/MatchController.ts, src/service/MatchmakingService/SearchController.ts, src/service/MatchmakingService/index.ts
-   Add fetch entries to matchmaking service (like search service but gets not only entity but also additional matchmaking data)
-   Jira: https://flowfact.atlassian.net/browse/FLOW-14943
=> Add Fetch entries in matchmaking service

src/http/APIClient.ts, src/service/EmailService/BodyController.ts, src/service/EmailService/ConfigurationController.ts, src/service/EmailService/NotificationController.ts, src/service/EmailService/RespondController.ts, src/service/EmailService/SendController.ts, src/service/EmailService/SyncController.ts, src/service/EmailService/index.ts, src/service/EntityService.ts, src/service/FieldCalculationService/index.ts, src/service/GeoInformationService/GeoInformationService.Types.ts, src/service/IS24PublishService/IS24Publish.Types.ts, src/service/IS24PublishService/IS24PublishController.ts, src/service/InteractiveExposeV2Service/InteractiveExposeV2Controller.ts, src/service/InteractiveExposeV2Service/TemplatesRepositoryController.ts, src/service/MailchimpSyncIntegrationService/MailchimpController.ts, src/service/MultimediaService/AlbumAssignmentController.ts, src/service/PlaceholderService/PlaceholderController.ts, src/service/PortalManagementService/CompanyEstateAttributesController.ts, src/service/PortalManagementService/index.ts, src/service/UserLogoutService/UserLogoutController.ts, src/service/UserLogoutService/UserLogoutService.Types.ts, src/service/common/types/TranslatableText.ts
Reverts FLOWFACT/ff-api-services#304
=> Revert "Refactor ApiClient for better types"

src/http/APIClient.ts, src/service/EmailService/BodyController.ts, src/service/EmailService/ConfigurationController.ts, src/service/EmailService/NotificationController.ts, src/service/EmailService/RespondController.ts, src/service/EmailService/SendController.ts, src/service/EmailService/SyncController.ts, src/service/EmailService/index.ts, src/service/EntityService.ts, src/service/FieldCalculationService/index.ts, src/service/GeoInformationService/GeoInformationService.Types.ts, src/service/IS24PublishService/IS24Publish.Types.ts, src/service/IS24PublishService/IS24PublishController.ts, src/service/InteractiveExposeV2Service/InteractiveExposeV2Controller.ts, src/service/InteractiveExposeV2Service/TemplatesRepositoryController.ts, src/service/MailchimpSyncIntegrationService/MailchimpController.ts, src/service/MultimediaService/AlbumAssignmentController.ts, src/service/PlaceholderService/PlaceholderController.ts, src/service/PortalManagementService/CompanyEstateAttributesController.ts, src/service/PortalManagementService/index.ts, src/service/UserLogoutService/UserLogoutController.ts, src/service/UserLogoutService/UserLogoutService.Types.ts, src/service/common/types/TranslatableText.ts
Reverts FLOWFACT/ff-api-services#306
=> Revert "Revert "Refactor ApiClient for better types""

package.json, src/service/ExcelExporterService/ExcelExporterController.ts
-  fixed function props
-   Jira: FLOW-15735
=> fix function props

src/service/ExcelExporterService/ExcelExporterController.ts, src/service/PortalManagementService/PortalEstateController.ts, src/service/PortalManagementService/PortalManagementService.Types.ts
- Fix the function method
- Fix the type
-   Jira: FLOW-16306
=> FLOW-16306

src/http/APIMapping.ts, src/index.ts, src/service/CsvDataToEntityImporterService/CsvDataToEntityImporter.Types.ts, src/service/CsvDataToEntityImporterService/CsvDataToEntityImporterController.ts, src/service/CsvDataToEntityImporterService/index.ts
-   Add new csv-data-to-entity-importer-service
-   Jira: https://flowfact.atlassian.net/browse/FLOW-15589
=> FLOW-15589

src/service/GeoInformationService/GeoInformationService.Types.ts, src/service/GeoInformationService/SearchController.ts
-   Added `countryCode` parameterem in polygons search
-   Jira: https://flowfact.atlassian.net/browse/FLOW-16711
=> feat FLOW-16711: countryCode param in polygons search

src/http/APIClient.ts, src/http/APIMapping.ts, src/index.ts, src/service/FeatureToggleService/FeatureToggleController.ts, src/service/FeatureToggleService/index.ts
- added featureToggleService
- adjusted response data to allow returning also "false"
-   Jira: FLOW-17407
=> FLOW-17407: add featureToggleService

src/service/GeoInformationService/GeoInformationService.Types.ts, src/service/GeoInformationService/SearchController.ts
Fetching Polygons update according to backend changes
=> FLOW-16305: Update Endpoint for fetching polygons list

src/service/UserService/UserService.Types.ts
-   ...
-   ...
-   ...
-   [x]  I have performed a self-review of my own code
-   Jira:https://jira.scout24.com/browse/CXGFF-309
=> Add ssoOrigin property

src/service/GeoInformationService/SearchController.ts
Revert `SearchController` changes until main PR is ready to be merged.
=> SearchController - revert api changes.

package.json, yarn.lock
-   update types to get ACP for EntityFields
- 
-   Jira: FLOW-18022
=> FLOW-18022: update types to get ACP for EntityFields

src/service/UserService/UserService.Types.ts
Add timezone to user model
-   [V ] My code follows the style guidelines of this project
-   [ V] I have performed a self-review of my own code
-   [ V] I have commented my code, particularly in hard-to-understand areas
-   [ V] My changes generate no new warnings (ESLint)
-   Jira: https://flowfact.atlassian.net/browse/FLOW-16059
=> FLOW-16059 Add timezone to user model

src/service/CompanyService/CompanyService.Types.ts
In the legislation texts creation form, I need to represent a new entity without an ID before it is saved.
-   Jira: https://flowfact.atlassian.net/browse/FLOW-17949
=> FLOW-17949 Make LegislationText ID optional for representing not saved entities

package.json, src/service/UserLogoutService/UserLoginPolicyController.ts, src/service/UserLogoutService/UserLogoutController.ts, src/service/UserLogoutService/UserLogoutService.Types.ts, src/service/UserLogoutService/index.ts
Login policy configuration.
There are some todo's left waiting for proper backend to be implemented, but we need to get this live before it will happen.
-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my own code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings (ESLint)
-   Jira: https://flowfact.atlassian.net/browse/FLOW-18142
=> FLOW-18142: Login policy configuration

src/service/PossibleValuesService/PossibleValuesController.ts
-   fix deletePossibleValue
-   Jira: NO-JIRA
=> NO-JIRA: fix deletePossibleValue

src/http/APIMapping.ts, src/index.ts, src/service/SwissLeadService/SwissLeadController.ts, src/service/SwissLeadService/SwissLeadService.Types.ts, src/service/SwissLeadService/index.ts
Endpoints needed for new integration with swiss lead service
-   Jira:
=> FLOW-14936 Create endpoints for swiss-lead-service

package.json, src/service/NylasService/NylasService.ts, yarn.lock
New in nylas service for shared email accounts
-   Jira:
=> FLOW-16441 New methods in nylas service for shared email accounts

src/service/SprengnetterService/SprengnetterController.ts
A new endpoint for Sprengnetter Quick Valuation
=> FLOW-18534 Add endpoint for Sprengnetter Quick Valuation

src/http/APIMapping.ts, src/service/SprengnetterGatewayService/SprengnetterGatewayController.ts, src/service/SprengnetterGatewayService/SprengnetterGatewayService.Types.ts, src/service/SprengnetterGatewayService/index.ts
- Added sprengnetter-gateway-service and its `createCustomerAccount`, `fetchCustomerAccount`, `deleteCustomerAccount` endpoints
-   Jira: FLOW-18475
=> feat FLOW-18475: sprengnetter-gateway-srv

src/service/MultimediaService/AlbumAssignmentController.ts
Just added one additional optional parameter to updateAssignments
-   Jira: https://flowfact.atlassian.net/browse/FLOW-17830
=> FLOW-17830: add short flag to multimedia assignment update

src/service/EmailService/SyncController.ts
-   ...
-   ...
-   ...
-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings (ESLint)
-   Jira:
=> FLOW-18863 - fix merging drafts

src/service/SprengnetterService/SprengnetterController.ts
New endpoint to fetch link to the valuation report in docx format
-   Jira: https://flowfact.atlassian.net/browse/FLOW-18811
=> FLOW-18811 Add endpoint to download docx report in sprengnetter

src/service/SchemaService.ts
=> FLOW-18834: add Integration types to old schema service

src/index.ts, src/service/SchemaService/SchemaService.Types.ts, src/service/SchemaService/SchemaService.ts, src/service/SchemaService/index.ts
-   ...
-   ...
-   ...
-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings (ESLint)
-   Jira:
=> FLOW-18834: better service exports

package.json, yarn.lock
-  updated types to add entity metadata creator
-   Jira: FLOW-18747
=> FLOW-18747: updated types

src/service/ViewDefinitionService/ViewDefinitionV2.Types.ts
Add optional "hints" field to view definition to be displayed in the table header
-   ...
-   ...
-   ...
-   Jira: https://jira.scout24.com/browse/CXGFF-427
=> feat CXGFF-394 - add hints

src/service/SprengnetterGatewayService/SprengnetterGatewayService.Types.ts
- Changes in the `Consent` interface
- Added `urls` field which will allow us to pass urls to i18next translations
- Used `Captions`
-   Jira:
=> feat FLOW-18475: consents changes

package.json, src/service/GeoInformationService/GeoInformationService.Types.ts, src/service/GeoInformationService/GeoPolygonController.ts, src/service/GeoInformationService/PolygonEntityLinkController.ts, src/service/GeoInformationService/SearchController.ts
Update Api for Matchmaking map update
-   Jira: https://flowfact.atlassian.net/browse/FLOW-14559
=> FLOW-10398: GeoPolygon api update

src/service/IS24EstateStatisticsService/IS24StatisticsController.ts, src/service/ViewDefinitionService/ViewDefinitionV2.Types.ts
New statistics type for IS24_STATISTICS
-   ...
-   ...
-   ...
-   Jira: https://jira.scout24.com/browse/CXGFF-393
=> feat CXGFF-393 - new statistics type

src/service/SprengnetterGatewayService/SprengnetterGatewayController.ts
- Added `login` endpoint
-   Jira:
=> feat FLOW-18475: login endpoint

src/service/SprengnetterGatewayService/LinkedCustomerAccountController.ts, src/service/SprengnetterGatewayService/SprengnetterGatewayService.Types.ts, src/service/SprengnetterGatewayService/UserConsentController.ts
- Adjustments after BE changes
- There's no need to change a major version because this service is not used anywhere yet
-   Jira:
=> feat FLOW-18475: adjustments after BE changes

src/service/IS24EstateStatisticsService/IS24StatisticsController.ts, src/service/IS24EstateStatisticsService/IS24StatisticsService.Types.ts, src/service/IS24EstateStatisticsService/index.ts
Wrap types in a namespace to prevent TS errors
-   ...
-   ...
-   ...
-   Jira: https://jira.scout24.com/browse/CXGFF-479, https://jira.scout24.com/browse/CXGFF-480
=> feat CXGFF-393 - pack types in namespace

src/service/IS24EstateStatisticsService/IS24StatisticsController.ts
Fix endpoint name for IS24 contact requests call
-   ...
-   ...
-   ...
-   Jira: https://jira.scout24.com/browse/CXGFF-480
=> feat CXGFF-393 - fix endpoint name

src/service/FlywheelService/TransactionController.ts
- Added endpoint to evaluate entry conditions
-   Jira: FLOW-18879
=> feat FLOW-18879: endpoint to evaluate entry conditions

src/service/CompanyService/CompanyService.Types.ts
-   added trialEnd to Company Type
-   Jira: FLOW-19257
=> added trialEnd to Company

src/service/FlywheelService/TransactionController.ts
- Adjustments in the evaluation endpoint after BE changes
- No need to increase major because this endpoint is not used anywhere yet
-   Jira: FLOW-19776
=> feat FLOW-19776: adjustments after BE changes

src/service/ViewDefinitionService/ViewDefinitionService.Types.ts, src/service/ViewDefinitionService/ViewDefinitionV2.Types.ts
A list specific ViewDefinitionV2Category configuration
-   ...
-   ...
-   ...
-   Jira: https://jira.scout24.com/browse/CXGFF-491
=> feat CXGFF-424 - new model for sortable config

src/http/APIMapping.ts, src/service/MaintenanceStatusService/MaintenanceStatus.Types.ts, src/service/MaintenanceStatusService/MaintenanceStatusController.ts, src/service/MaintenanceStatusService/index.ts
Added new service to retrieve data about our maintenance status
-   Jira: https://flowfact.atlassian.net/browse/FLOW-19967
=> FLOW-19967: add maintenance-status-lambda

src/index.ts
Added missing export
-   Jira: https://flowfact.atlassian.net/browse/FLOW-19967
=> FLOW-19967: added export

src/service/UserService/UserService.Types.ts
- `USER_AGENT` role has been added. It's needed for Franchise customers like Debeka
-   Jira: FLOW-19824
=> feat FLOW-19824: add USER_AGENT role

src/service/PreconditionService/NylasPreconditionController.ts
Matching PR for https://github.com/FLOWFACTCorp/platform-apps/pull/2919/files
-   Jira: https://flowfact.atlassian.net/browse/FLOW-20474
=> FLOW-20474: Add new endpoint for company us nylas accounts

src/service/EntityService.ts
- Added deep PATCH of an entity
-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my own code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings (ESLint)
-   Jira: FLOW-20193
=> feat FLOW-20193: deep PATCH entity

src/service/InteractiveExposeV2Service/InteractiveExposeV2Service.Types.ts
A new property "isDefault" should be added to IEXv2 email templates in order to configure which email template should be rendered if the user didn't specify any, or in the exposés sent by automation.
-   Jira: https://flowfact.atlassian.net/browse/FLOW-20469
=> FLOW-20469 Add a new property "isDefault" to IEXv2 email templates

src/service/IS24EstateStatisticsService/IS24StatisticsController.ts, src/service/IS24EstateStatisticsService/IS24StatisticsService.Types.ts
Display homeowner requests on dashboard inside new KPI widget
-   Jira: https://jira.scout24.com/browse/CXGFF-556
=> CXGFF-556: request response for home owner leads

src/service/InquiryService.ts
-   Jira: https://flowfact.atlassian.net/browse/FLOW-20493
=> FLOW-20493: added contact api endpoints to inquiry service

package.json, src/service/NylasContactSyncService.ts, yarn.lock
Nylas contacts sync new endpoint.
-   Jira: https://flowfact.atlassian.net/browse/FLOW-20895
=> FLOW-20875: Nylas sync new endpoint

src/service/PortalManagementService/PortalManagementService.Types.ts
-   extend PortalEstateSettings type
-   Jira: FLOW-20058
=> FLOW-20058: extend PortalEstateSettings type

src/service/CompanyService/InternalController.ts
-   added an internal endpoint to fetch a company by its id
=> find company by id internal

src/service/MatchmakingService/Matchmaking.Types.ts
Now the matching criteria percentage will be calculated by **matchmaking-service** instead of the frontend.
This new field will hold this calculated value to be served to the UI.
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   Jira: https://flowfact.atlassian.net/browse/FLOW-20089
=> FLOW-20089 Add a property for storing the optional criteria matching percentage

src/service/DynamicLayoutService/NavigationTypes.ts, src/service/DynamicLayoutService/WidgetLayoutTypes.ts
- added LayoutActionType
- added actions key to BaseWidgetLayout 
-   Jira: https://flowfact.atlassian.net/browse/FLOW-21325
=> FLOW-21325: extended WidgetLayout type

src/http/APIMapping.ts, src/index.ts, src/service/GetResponseSyncIntegrationService/GetResponseController.ts, src/service/GetResponseSyncIntegrationService/GetResponseService.Types.ts, src/service/GetResponseSyncIntegrationService/index.ts
-   ...
-   ...
-   ...
-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings (ESLint)
-   Jira:
=> FLOW-21915 Activate GetResponse interface

src/service/SearchService.ts
-   Jira: https://flowfact.atlassian.net/browse/FLOW-22296
=> FLOW-22296: add error handling to count in SearchService

src/service/MatchmakingService/Matchmaking.Types.ts
=> FLOW-22217 Added Prospect Types

src/service/FlowfactImporterService/CustomMappingController.ts
Add missing fetch all mapings
-   Jira: https://flowfact.atlassian.net/browse/FLOW-22166
=> FLOW-22166 Fetch all mappings

src/service/FlowfactImporterService/CustomMappingController.ts, src/service/FlowfactImporterService/FlowfactImporterService.Types.ts
Fetch correct type for all custom mappings
-   Jira:
=> FLOW-22166 Fetch correct type for all custom mappings

src/service/MatchmakingService/ProspectController.ts
prepare api calls for search-profiles CRUD operations
=> Flow 21561

src/http/APIMapping.ts, src/index.ts, src/service/SurveyService/Survey.Types.ts, src/service/SurveyService/SurveyController.ts, src/service/SurveyService/index.ts
Add survey-service
-   Jira: https://flowfact.atlassian.net/browse/FLOW-22577
=> Flow 22577

src/service/FlowfactImporterService/RawUploaderController.ts, src/service/FlowfactImporterService/index.ts
Add new endpoint to upload raw exporter files to s3
=> FLOW-22166 Create endpoint to upload raw exporter files to s3

src/service/MatchmakingService/Matchmaking.Types.ts
Bugfixes after testing party.
-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my own code
-   [X] I have commented my code, particularly in hard-to-understand areas
-   [X] My changes generate no new warnings (ESLint)
=> FLOW-22870: prepare new fields

src/service/DynamicLayoutService/WidgetLayoutSnapshotController.ts, src/service/DynamicLayoutService/WidgetLayoutTypes.ts, src/service/DynamicLayoutService/index.ts
- Endpoint for fetching Dynamic Layout history. It contains layout snapshots saved when changes had been made to the layout.
- Interfaces for layout snapshot object and pagination. Also `BaseWidgetLayout` is extended with update comment field that is now filled when user changes the widget layout.
-   Jira: [https://flowfact.atlassian.net/browse/FLOW-22662](https://flowfact.atlassian.net/browse/FLOW-22662)
-  Confluence: [Solution Layout History Version control concept](https://flowfact.atlassian.net/wiki/spaces/RD/pages/3562143745/Solution+-+Layout+H …
=> FLOW-22662 Fetching layout history
